# Generated by Django 5.1 on 2024-08-23 20:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="друзья"
            ),
        ),
        migrations.CreateModel(
            name="FriendshipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("отправлено", "Sent"),
                            ("принято", "Accepted"),
                            ("отклонено", "Rejected"),
                        ],
                        default="отправлено",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_friendshiprequests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="отправитель",
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friendshiprequests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос в друзья",
                "verbose_name_plural": "Запросы в друзья",
                "ordering": ["-created_at"],
            },
        ),
    ]
