# Generated by Django 5.1 on 2024-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_like_options_post_comments_count_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True, to="posts.comment", verbose_name="комментарии"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="comments_count",
            field=models.IntegerField(
                default=0, verbose_name="количество комментариев"
            ),
        ),
    ]
